import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Footer from "../components/Footer";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>{props.heroCourseData.details.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero heroCourseData={props.heroCourseData} faqData={props.faqData} />

      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
  const urls = [
    "https://api.acharyaprashant.org/v2/legacy/courses/series/optuser/course-series-eeb9d3",
    "https://api.acharyaprashant.org/v2/legacy/courses/tags",
    "https://api.acharyaprashant.org/v2/legacy/courses/faqs?language=english",
  ];
  const res = await fetch(urls["0"]);

  const heroCourseData = await res.json();

  const res2 = await fetch(urls["2"]);
  const faqData = await res2.json();
  return {
    props: { heroCourseData, faqData },
  };
}
